#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER "$DJANKISERV_USERDB_USER" PASSWORD '$DJANKISERV_USERDB_PASSWORD';
    CREATE DATABASE "$DJANKISERV_USERDB_NAME" owner $DJANKISERV_USERDB_USER;
    GRANT ALL PRIVILEGES ON DATABASE "$DJANKISERV_USERDB_NAME" TO "$DJANKISERV_USERDB_USER";
EOSQL
