#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER "$DJANKISERV_MAINDB_USER" PASSWORD '$DJANKISERV_MAINDB_PASSWORD';
    CREATE DATABASE "$DJANKISERV_MAINDB_NAME" owner $DJANKISERV_MAINDB_USER;
    GRANT ALL PRIVILEGES ON DATABASE "$DJANKISERV_MAINDB_NAME" TO "$DJANKISERV_MAINDB_USER";
EOSQL
